name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies with uv
        run: |
          pip install uv
          uv sync --all-extras --dev


      - name: Run tests with coverage
        run: |
          pytest --cov=libraries_database --cov-report=xml
