name: Django Test Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies with uv
        run: |
          pip install uv
          uv sync --all-extras --dev

      - name: Run tests with coverage
        run: |
          source venv/bin/activate
          pytest --cov=libraries_database
